---
# tasks file for ansible-openresty
- name: Ensure nobody group exists.
  group:
    name: nobody
    state: present

- name: Create dir '{{ install_dir }}'
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Unarchive package {{ package_name }}
  unarchive:
    src: "{{ package_name }}"
    dest: "{{ install_dir }}"
    extra_opts: "--strip-components=1"

- name: Genreate openresty systemd file
  template:
    src: openresty.service.j2
    dest: /etc/systemd/system/openresty.service
  notify: Restart openresty service

- name: Start openresty service
  systemd:
    name: openresty
    state: started
    daemon_reload: yes
  tags: start

- name: Restart openresty service
  systemd:
    name: openresty
    state: restarted
    daemon_reload: yes
  tags: restart,never

- name: Stop openresty service
  systemd:
    name: openresty
    state: stopped
    daemon_reload: yes
  tags: stop,never

- name: Reload openresty service
  systemd:
    name: openresty
    state: stopped
    daemon_reload: yes
  tags: reload,never

- name: Uninstall openresty
  shell: |
    systemctl stop openresty | true
    ps -ef | grep '{{ install_dir }}' | grep -v grep | awk '{print $2}' | xargs -i kill -9 {}
    kill -9 $(ps -ef | grep '{{ install_dir }}' | grep -v grep | awk '{print $2}')
    \rm -rf {{ install_dir }}
  tags: uninstall,never